// <auto-generated />
namespace BookReview.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1qwe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1qwe));
        
        string IMigrationMetadata.Id
        {
            get { return "202108111628262_1qwe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
